src/DevInSantosMVC.Site/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using DevInSantosMVC.Domain.Model.Entities;
using DevInSantosMVC.Domain.Model.Interfaces;
using DevInSantosMVC.Site.Src.Filters;
using DevInSantosMVC.Site.Models;

namespace DevInSantosMVC.Site.Controllers
{
    public class UserController : BaseController
    {
        public IQuestions Questions { get; set; }
        public IUsers Users { get; set; }

        public UserController()
            : this(DependencyResolver.Current.GetService<IUsers>(),
            DependencyResolver.Current.GetService<IQuestions>())
        {
        }

        public UserController(IUsers users, IQuestions questions)
        {
            Users = users;
            Questions = questions;
        }
        
        [NullFilter("user", "Error")]
        public ViewResult UserProfile(User user)
        {   
            return View("Profile", user);
        }

        [HttpPost]
        [NullFilter("user", "Error")]
        public ActionResult Ask(User user, string question)
        {
            var newQuestion = new Question(CurrentUser, user, question);
            Questions.Add(newQuestion);
            return ExtendedJson(new { success = true, message = "Pergunta enviada com sucesso!" });
        }

        [Authorize]
        [NullFilter("user", "Error")]
        public ActionResult InBox(User user) {
            return View("Inbox", user);
        }

        [HttpPost]
        [NullFilter("question", "Error")]
        public ActionResult Answer(Question question, string answer)
        {
            question.Answer = answer;
            Questions.Update(question);
            return ExtendedJson(new { success = true, message = "Pergunta respondida com sucesso!" });
        }

        [HttpPost]
        [NullFilter("question", "Error")]
        public ActionResult Remove(Question question) {
            Questions.Remove(question);
            return ExtendedJson(new { success = true, message = "Pergunta removida com sucesso!" });
        }

        public ActionResult ListAllUsers() {
            var users = Users.FindAll().ToList();
            return View(users);
        }
    }
}

src/DevInSantosMVC.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/themes/base/css", "~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <a href="/"><img src="~/Images/devinsantos.png" alt="DevInSantos" /></a>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            @if (Request.IsAuthenticated)
                            { 
                                <li><a href="@Url.ForUser(User.Identity.Name, "InBox")">InBox</a></li>
                                <li><a href="@Url.ForUser(User.Identity.Name)">Profile</a></li>
                            }else{
                                <li>@Html.ActionLink("About", "About", "Home")</li>
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            }
                            <li>@Html.ActionLink("Users", "ListAllUsers", "User")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/master")
        @RenderSection("scripts", required: false)
    </body>
</html>